// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgsT-8S8aXVACdfgdWyaTbj-xn-A-Lmd4',
    appId: '1:300734801366:web:7369a20f118134e6a23077',
    messagingSenderId: '300734801366',
    projectId: 'fir-flutter-codelab-d1763',
    authDomain: 'fir-flutter-codelab-d1763.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-d1763.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD12EHYlY9I6hWeWKsbcYCLe_D8U6DZqFY',
    appId: '1:300734801366:android:0a3a5b5528aacc02a23077',
    messagingSenderId: '300734801366',
    projectId: 'fir-flutter-codelab-d1763',
    storageBucket: 'fir-flutter-codelab-d1763.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPEwzhf1x7tykYh_UyNIZy2tEj1bXCsbU',
    appId: '1:300734801366:ios:51344f8a7ba1cff4a23077',
    messagingSenderId: '300734801366',
    projectId: 'fir-flutter-codelab-d1763',
    storageBucket: 'fir-flutter-codelab-d1763.appspot.com',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPEwzhf1x7tykYh_UyNIZy2tEj1bXCsbU',
    appId: '1:300734801366:ios:51344f8a7ba1cff4a23077',
    messagingSenderId: '300734801366',
    projectId: 'fir-flutter-codelab-d1763',
    storageBucket: 'fir-flutter-codelab-d1763.appspot.com',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgsT-8S8aXVACdfgdWyaTbj-xn-A-Lmd4',
    appId: '1:300734801366:web:f054af9543c6ca44a23077',
    messagingSenderId: '300734801366',
    projectId: 'fir-flutter-codelab-d1763',
    authDomain: 'fir-flutter-codelab-d1763.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-d1763.appspot.com',
  );
}
